// Generated by Solara
import android.graphics.Color
import java.io.Serializable


data class MySampleContent(
  val example: String,
  val asJson: String = "{\"example\":\"Example\"}",
): Serializable {
  companion object {
    val instance = MySampleContent(
      example = "Example"
    )
  }
}


