// Generated by Solara
import 'dart:convert';
import 'package:flutter/material.dart';


class MySampleContent {
  final String example;
  final String asJson = "{\"example\":\"Example\"}";
  const MySampleContent({
     required this.example});

  static const MySampleContent instance = MySampleContent(
    example: "Example"
  );

  factory MySampleContent.fromJson(Map<String, dynamic> json) {
    return MySampleContent(
      example: json['example']
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'example': example
    };
  }

  String toJsonString() {
    return json.encode(toJson());
  }

  static MySampleContent? fromJsonString(String jsonString) {
    try {
      final Map<String, dynamic> jsonMap = json.decode(jsonString);
      return MySampleContent.fromJson(jsonMap);
    } catch (e) {
      print('Error parsing JSON: $e');
      return null;
    }
  }
}


